CREATE ROLE _user_role;
GRANT ALL ON filters TO _user_role;
GRANT ALL ON passengers TO _user_role;
GRANT SELECT, INSERT ON tickets TO _user_role;
GRANT SELECT ON places TO _user_role;
GRANT SELECT ON railcars TO _user_role;
GRANT SELECT ON railcars_in_trains TO _user_role;
GRANT SELECT ON races TO _user_role;
GRANT SELECT ON schedule TO _user_role;
GRANT SELECT, INSERT ON train_comments TO _user_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO _user_role;

CREATE ROLE _carrier_role;
GRANT SELECT, INSERT ON places TO _carrier_role;
GRANT SELECT, INSERT, UPDATE ON races TO _carrier_role;
GRANT SELECT, INSERT ON railcars TO _carrier_role;
GRANT SELECT, INSERT ON railcars_in_trains TO _carrier_role;
GRANT SELECT, INSERT ON schedule TO _carrier_role;
GRANT SELECT, INSERT ON tickets TO _carrier_role;
GRANT SELECT ON train_comments TO _carrier_role;
GRANT SELECT, INSERT ON trains TO _carrier_role;
GRANT SELECT ON users_view TO _carrier_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO _carrier_role;

CREATE ROLE _admin_role;
GRANT ALL ON filters TO _admin_role;
GRANT ALL ON passengers TO _admin_role;
GRANT SELECT, INSERT ON places TO _admin_role;
GRANT SELECT, INSERT, UPDATE ON races TO _admin_role;
GRANT SELECT, INSERT ON railcars TO _admin_role;
GRANT SELECT, INSERT ON railcars_in_trains TO _admin_role;
GRANT SELECT, INSERT ON schedule TO _admin_role;
GRANT SELECT, INSERT ON tickets TO _admin_role;
GRANT ALL ON train_comments TO _admin_role;
GRANT SELECT, INSERT ON trains TO _admin_role;
GRANT SELECT ON users_view TO _admin_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO _admin_role;

CREATE ROLE _system_role;
GRANT SELECT ON filters TO _system_role;
GRANT SELECT ON passengers TO _system_role;
GRANT SELECT ON places TO _system_role;
GRANT SELECT ON races TO _system_role;
GRANT SELECT ON railcars TO _system_role;
GRANT SELECT ON railcars_in_trains TO _system_role;
GRANT SELECT ON schedule TO _system_role;
GRANT SELECT ON tickets TO _system_role;
GRANT SELECT ON train_comments TO _system_role;
GRANT SELECT ON trains TO _system_role;
GRANT ALL ON users_view TO _system_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO _system_role;
