server:
    host: localhost
    port: 8080
    timeout: 30000
database:
    type: postgresql
    url: jdbc:postgresql://localhost:5432/train_tickets_postgres
    username: train_database_admin
    password: s3cr3tpassw0rd
    poolSize: 20
security:
    secret: s3cr3tc0d3
    expiration: 1
    userRole: user_role
    carrierRole: carrier_role
    adminRole: admin_role
redis:
    host: localhost
    port: 6379
    password: s3cr3tr3d1s
log:
    level: DEBUG