server:
    host: localhost
    port: 8080
    timeout: 30000
database:
    type: postgresql
    params:
       host: localhost
       port: 5432
       name: train_tickets_postgres
       username: train_database_admin
       password: s3cr3tpassw0rd
       poolSize: 20
#    type: mongodb
#    params:
#        host: localhost
#        port: 27017
#        name: train_tickets_mongo
#        username: train_database_admin
#        password: s3cr3tpassw0rd
#        poolSize: 20
#        replicaSet: rs0
security:
    secret: s3cr3tc0d3
    expiration: 1
    userRole: user_role
    carrierRole: carrier_role
    adminRole: admin_role
redis:
    host: localhost
    port: 6379
    password: s3cr3tr3d1s
log:
    level: DEBUG
