rootProject.name = "traintickets"
include(":business-logic")
include(":di")
include(":data-access")
include(":security")
include("control")
include(":jdbc")
include(":payment")
include(":user-interface")
include(":logger")
